Branch hw 03
Dima-Penzev/goit-markup-hw-03 pull request #1
Opened 2020-12-26 19:05 UTC by Dima-Penzev

2020-12-26 19:22 UTC, magom001 requested changes

2020-12-26 19:22 UTC, magom001 commented on css/styles.css
> +* {
'*' ? Давай явно перечислим, чему ты эти стили хочешь применить

2020-12-26 19:22 UTC, magom001 commented on css/styles.css
> +.container{
с форматированием у тебя опять какая-то лажа. Должен быть пробел перед '{'

2020-12-26 19:22 UTC, magom001 commented on css/styles.css
> +.header-nav .item + .item{
я с трудом понимаю смысл этого селектора. Можешь пояснить задумку?

2020-12-26 19:22 UTC, magom001 commented on css/styles.css
> +  text-align: center;
Давай будем консистентны. Используешь flex - используй justify-content для выравнивания.

2020-12-26 19:22 UTC, magom001 commented on css/styles.css
> +  background-color: #ffffff;
цвет в переменную

2020-12-26 19:22 UTC, magom001 commented on css/styles.css
> +  box-shadow: 0 1px 3px var(--team-item-shadow-first),
это ты прям изрядно перемудрил
просто сделай переменную `--default-box-shadow: ...`, скопируй туда значение из фигмы

2020-12-26 19:22 UTC, magom001 commented on css/styles.css
> +  box-shadow: 0 1px 3px var(--team-item-shadow-first),
кстати, в hero на кнопке тоже есть тень. Ее все забывают.

2020-12-26 19:22 UTC, magom001 commented on css/styles.css
> +  /* width: calc((100%-60px)/3); */
ненужный код удаляй

2020-12-26 19:22 UTC, magom001 commented on css/styles.css
> +.portfolio-item:nth-last-child(-n+3){
что будет, если кол-во карточек станет не 9, а 8?

2020-12-26 20:01 UTC, Dima-Penzev commented on css/styles.css
> +.header-nav .item + .item{
Я этот прием увидел в наших видеолекциях (соседние селекторы). Я это применил это, чтобы не подчищать правый марджин в списке навигации. А затем я сделал левый марджин блоку header-nav, чтобы отступить от лого

2020-12-26 20:15 UTC, Dima-Penzev commented on css/styles.css
> +.portfolio-item:nth-last-child(-n+3){
У 6ой карточки нижнего марджина не будет...(

2020-12-28 13:47 UTC, magom001 approved these changes

2020-12-28 14:40 UTC, merged